name: Budowanie Pluginu

on:
  push:
    branches: [ "main" ] # Uruchomi się przy każdym zapisie kodu
  workflow_dispatch:      # Pozwala uruchomić budowanie ręcznie przyciskiem

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Budowanie pliku JAR (Maven)
      run: mvn -B package --file pom.xml

    - name: Gotowy plik do pobrania
      uses: actions/upload-artifact@v4
      with:
        name: SupplyDrop-Plugin
        path: target/*.jar
